### ISSUE TITLE
KeyError: 'LoadResizeImageMask'

### ISSUE THREAD

**Issue by bingling00** [jmkl/comfyui-photoshop#2]
got prompt
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/Users/ziang/miniconda3/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ziang/miniconda3/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ziang/miniconda3/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ziang/Downloads/ComfyUI-master/server.py", line 46, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ziang/Downloads/ComfyUI-master/server.py", line 469, in post_prompt
    valid = execution.validate_prompt(prompt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ziang/Downloads/ComfyUI-master/execution.py", line 598, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
             ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'LoadResizeImageMask'

**Comment by bingling00** [comment]
Why did this error occur? I only installed the photoshop plugin, do I need to install any other ones?

**Comment by flipnism** [comment]
unfortunately, i messed up.. im writing the plugin from scratch... you can find it here https://github.com/flipnism/comfyshop
